<!--source .venv/bin/activate-->

<!--source .venv/bin/activate-->

```{r, include=FALSE, cache=F}
knitr::read_chunk('chunk_setup.R')
```

```{r, setup, echo=FALSE,include=F}
```

```{=html}
<!--connect dvisvgm to Ghostscript for tikz
find gs, run: tools:find_gs_cmd()
-->
```
```{r point-to-ghostscript, include=FALSE}
Sys.setenv(LIBGS = "/usr/local/bin/gs")
```

<!--Conditional tikz output types; use PDF if this is LaTeX, otherwise use SVG with embedded fonts -->

```{r tikzsetup, include=FALSE}
if (knitr::is_latex_output()) {
  knitr::opts_template$set(
    tikz_settings = list(fig.ext = "pdf", fig.align = "center")
  )
} else {
  knitr::opts_template$set(
    tikz_settings = list(fig.ext = "svg", fig.align = "center",
                         engine.opts = list(dvisvgm.opts = "--font-format=woff"))
  )
}
```

```{r, include=FALSE, cache=FALSE}
knitr::read_chunk('chunk_algorithmengine.R')
```

```{r, algorithmengine, echo=FALSE}
```

```{r, connect-db, echo=FALSE}
```

```{r, include=FALSE, cache=FALSE}
knitr::read_chunk('chunk_setup_db_module.py')
```

```{python python-module-db, echo=FALSE}
```

---
title: "Home"
execute:
  warning: false
  results: hold
---

```{mermaid}
graph TB
    w1-->a(Machine Learning Types)-->|walkthrough|a1(k-Nearest Neighbors Classification)-->|term|a2(Confusion Matrix)-->|term, scikit-learn|a3(Performance Metrics)-->|hands-on|a4(Performing Model Evaluation)-->|evaluation method|a5(K-Fold Cross-Validation)-->|term technique coding|a6(Model Selection)-->|technique coding|a7(Hyperparameter Tuning)
    
    p1-->b(help Command)-->b1(Functions/Methods 1)-->b2(Functions/Methods 2)-->b3(Random Number Generation)-->b4(Module Programming)-->b5(A Game of Chance Craps)-->b6(The Tortoise and the Hare)


    a1-->s1[py-script<br>Jupyter-Notebook<br>Colab<br>NumPy Scikit-Learn Pandas Seaborn Matplotlib];a2-->s1;a3-->s1;a4-->s1
    style w1 fill:#80deb2,stroke:#333,stroke-width:2px
    style w2 fill:#80deb2,stroke:#333,stroke-width:2px
    style w3 fill:#80deb2,stroke:#333,stroke-width:2px
    style s1 fill:#e4c9b4,stroke:#333,stroke-width:2px
    style p1 fill:#e4c9b4,stroke:#333,stroke-width:2px
```


