---
title: Mathematical Concepts
---

## Interval {#sec-mathinterval}

1.  **Interval/range**: The set of all real numbers between two given numbers. The two numbers on the ends are the **endpoint**s. The endpoints might or might not be included in the interval depending whether the interval is `open` or `closed`.

2.  **Inclusive**: Including the endpoints of an interval. For example, `the interval from 1 to 10, inclusive` means the closed interval written $[1, 10]$.

3.  **Exclusive**: Excluding the endpoints of an interval. For example, `the interval from 1 to 10, exclusive` means the open interval written $(1, 10)$.

Four types:

-   $[1, 10]$: the interval between 1 and 10, inclusive
-   $[1, 10)$: the interval between 1 inclusive and 10 exclusive
-   $(1, 10]$: the interval between 1 exclusive and 10, inclusive
-   $(1, 10)$: the interval between 1 and 10, exclusive

## Combinations

## Cartesian Coordinate & Distance {#sec-cartesiansys}

A **Cartesian coordinate system** in a plane is a coordinate system that specifies each point uniquely by a pair of numerical coordinates, which are the `signed distances` to the point from two fixed perpendicular oriented lines, measured in the same unit of length.

Distance:

## Measure of Central Tendency

In statistics, **outlier**s are values out of the ordinary and possible way out of the ordinary. Sometimes, outliers are simply bad data. In the data science case studies, we'll see that outliers can distort results. Which of the three measures of central tendency we discussed---**mean**, **median** and **mode**---is most affected by outliers? Why? Which of these measures are not affected or least affected? Why?

<!--
```{bash eval=FALSE,echo=FALSE}
 Outliers affect mean the most. Mean is the sum of a collection of values divided by the count of values in the data. So if the value of the outlier is high it increases the mean, and if the value of outlier is low it decreases the mean. Eg: Suppose you hade the values 2,2,3,4,23 . The 23 (an outlier) being so different to the others it will drag the mean much higher than it would otherwise have been. It may even be a false reading or something like that. It is things such as this that makes Statistics more of a challenge sometimes. It is imperative that thought be given to the context of the numbers you are investigating.

Outliers have a little effect on Median because is the average amount in a set of data, and in that case an outlier would affect the data, because it would cause the results to be significantly higher or lower than the average if it was all the numbers except the outlier.

Mode remain the same, as these are all resistant to outliers. Mode is the number that occurs most often, so an outlier would not really have any impact because there is no equation involve.
```
-->

## Measure of Dispersion

## Correlation

## Concurrence

## Probability/Likelihood

## Bayes Theorem
